// Generated by CoffeeScript 1.8.0
(function() {
  window.Agent = (function() {
    var CENTER;

    CENTER = new PIXI.Point(0.5, 0.5);

    function Agent(texture) {
      this.graphics = new PIXI.Sprite(texture);
      this.graphics.anchor = CENTER;
      this.graphics.scale.x = this.graphics.scale.y = 0.8;
      this.graphics.position = new PIXI.Point(0, -10);
      this.step = 0;
    }

    Agent.prototype.tick = function() {
      this.step += 1;
      return this.graphics.rotation = Math.sin(this.step * 0.1) * 0.2;
    };

    return Agent;

  })();

}).call(this);

//# sourceMappingURL=agent.js.map
