// Generated by CoffeeScript 1.8.0
(function() {
  window.Cell = (function() {
    var CENTER;

    CENTER = new PIXI.Point(0.5, 0.5);

    Cell.TEXTURES_BY_TYPE = {};

    Cell.capitalise = function(string) {
      return string[0].toUpperCase() + string.slice(1).toLowerCase();
    };

    Cell.textureFromType = function(type) {
      var file, t;
      t = window.Cell.TEXTURES_BY_TYPE[type];
      if (t == null) {
        file = "png/hex/Tiles/tile" + (window.Cell.capitalise(type)) + ".png";
        t = window.Cell.TEXTURES_BY_TYPE[type] = PIXI.Texture.fromImage(file);
      }
      return t;
    };

    function Cell(x, y, center, type, grid) {
      this.x = x;
      this.y = y;
      this.center = center;
      this.type = type;
      this.grid = grid;
      this.bg = new PIXI.Sprite(window.Cell.textureFromType(this.type));
      this.bg.anchor = CENTER;
      this.bg.position = this.center;
      this.grid.addChild(this.bg);
    }

    Cell.prototype.add = function(agent) {
      this.child = agent.graphics;
      return this.bg.addChild(this.child);
    };

    Cell.prototype.clear = function() {
      return this.bg.removeChild(this.child);
    };

    return Cell;

  })();

}).call(this);

//# sourceMappingURL=cell.js.map
